//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 12:16:45 PM GST 
//


package com.flydubai.dataservices.flight.common.vo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AirlineCode"/>
 *         &lt;element ref="{}FlightNumber"/>
 *         &lt;element ref="{}CodeSharing" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OperatingCarrier" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}AirlineCode"/>
 *                   &lt;element ref="{}FlightNumber"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}status"/>
 *         &lt;element name="AircraftOwner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Route" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}Date"/>
 *         &lt;element ref="{}remarks"/>
 *         &lt;element name="ModifyAction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ModifyReason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}LastModifedDateLTC"/>
 *         &lt;element ref="{}LastModifedDateUTC"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "airlineCode",
    "flightNumber",
    "codeSharing",
    "operatingCarrier",
    "status",
    "aircraftOwner",
    "route",
    "date",
    "remarks",
    "modifyAction",
    "modifyReason",
    "lastModifedDateLTC",
    "lastModifedDateUTC"
})
@XmlRootElement(name = "Flight")
public class Flight {

    @XmlElement(name = "AirlineCode", required = true)
    protected String airlineCode;
    @XmlElement(name = "FlightNumber", required = true)
    protected FlightNumberWithSuffixType flightNumber;
    @XmlElement(name = "CodeSharing")
    protected List<CodeSharing> codeSharing;
    @XmlElement(name = "OperatingCarrier")
    protected Flight.OperatingCarrier operatingCarrier;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(name = "AircraftOwner", required = true)
    protected String aircraftOwner;
    @XmlElement(name = "Route", required = true)
    protected String route;
    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(required = true)
    protected String remarks;
    @XmlElement(name = "ModifyAction", required = true)
    protected String modifyAction;
    @XmlElement(name = "ModifyReason", required = true)
    protected String modifyReason;
    @XmlElement(name = "LastModifedDateLTC", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifedDateLTC;
    @XmlElement(name = "LastModifedDateUTC", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifedDateUTC;

    /**
     * Gets the value of the airlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirlineCode() {
        return airlineCode;
    }

    /**
     * Sets the value of the airlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirlineCode(String value) {
        this.airlineCode = value;
    }

    /**
     * Gets the value of the flightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link FlightNumberWithSuffixType }
     *     
     */
    public FlightNumberWithSuffixType getFlightNumber() {
        return flightNumber;
    }

    /**
     * Sets the value of the flightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightNumberWithSuffixType }
     *     
     */
    public void setFlightNumber(FlightNumberWithSuffixType value) {
        this.flightNumber = value;
    }

    /**
     * Code sharing group
     * 
     * Note: this will list all code share flights provided by OAG.  Any Operating Carrier data must be mapped to the new node "Operating Carrier",  introduced 03Feb2011 Gets the value of the codeSharing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codeSharing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodeSharing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeSharing }
     * 
     * 
     */
    public List<CodeSharing> getCodeSharing() {
        if (codeSharing == null) {
            codeSharing = new ArrayList<CodeSharing>();
        }
        return this.codeSharing;
    }

    /**
     * Gets the value of the operatingCarrier property.
     * 
     * @return
     *     possible object is
     *     {@link Flight.OperatingCarrier }
     *     
     */
    public Flight.OperatingCarrier getOperatingCarrier() {
        return operatingCarrier;
    }

    /**
     * Sets the value of the operatingCarrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flight.OperatingCarrier }
     *     
     */
    public void setOperatingCarrier(Flight.OperatingCarrier value) {
        this.operatingCarrier = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the aircraftOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftOwner() {
        return aircraftOwner;
    }

    /**
     * Sets the value of the aircraftOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftOwner(String value) {
        this.aircraftOwner = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoute(String value) {
        this.route = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the modifyAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifyAction() {
        return modifyAction;
    }

    /**
     * Sets the value of the modifyAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifyAction(String value) {
        this.modifyAction = value;
    }

    /**
     * Gets the value of the modifyReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifyReason() {
        return modifyReason;
    }

    /**
     * Sets the value of the modifyReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifyReason(String value) {
        this.modifyReason = value;
    }

    /**
     * Gets the value of the lastModifedDateLTC property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifedDateLTC() {
        return lastModifedDateLTC;
    }

    /**
     * Sets the value of the lastModifedDateLTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifedDateLTC(XMLGregorianCalendar value) {
        this.lastModifedDateLTC = value;
    }

    /**
     * Gets the value of the lastModifedDateUTC property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifedDateUTC() {
        return lastModifedDateUTC;
    }

    /**
     * Sets the value of the lastModifedDateUTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifedDateUTC(XMLGregorianCalendar value) {
        this.lastModifedDateUTC = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}AirlineCode"/>
     *         &lt;element ref="{}FlightNumber"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "airlineCode",
        "flightNumber"
    })
    public static class OperatingCarrier {

        @XmlElement(name = "AirlineCode", required = true)
        protected String airlineCode;
        @XmlElement(name = "FlightNumber", required = true)
        protected FlightNumberWithSuffixType flightNumber;

        /**
         * Gets the value of the airlineCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAirlineCode() {
            return airlineCode;
        }

        /**
         * Sets the value of the airlineCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAirlineCode(String value) {
            this.airlineCode = value;
        }

        /**
         * Gets the value of the flightNumber property.
         * 
         * @return
         *     possible object is
         *     {@link FlightNumberWithSuffixType }
         *     
         */
        public FlightNumberWithSuffixType getFlightNumber() {
            return flightNumber;
        }

        /**
         * Sets the value of the flightNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link FlightNumberWithSuffixType }
         *     
         */
        public void setFlightNumber(FlightNumberWithSuffixType value) {
            this.flightNumber = value;
        }

    }

}
