//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 12:05:22 PM GST 
//


package com.flydubai.dataservices.flight.common.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}BoardAirportCode"/>
 *         &lt;element ref="{}OffAirportCode"/>
 *         &lt;element name="SSRCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}LastModifedDateLTC"/>
 *         &lt;element ref="{}LastModifedDateUTC"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "boardAirportCode",
    "offAirportCode",
    "ssrCode",
    "lastModifedDateLTC",
    "lastModifedDateUTC"
})
@XmlRootElement(name = "RestrictedSSR")
public class RestrictedSSR {

    @XmlElement(name = "BoardAirportCode", required = true)
    protected String boardAirportCode;
    @XmlElement(name = "OffAirportCode", required = true)
    protected String offAirportCode;
    @XmlElement(name = "SSRCode", required = true)
    protected String ssrCode;
    @XmlElement(name = "LastModifedDateLTC", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifedDateLTC;
    @XmlElement(name = "LastModifedDateUTC", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifedDateUTC;

    /**
     * Gets the value of the boardAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoardAirportCode() {
        return boardAirportCode;
    }

    /**
     * Sets the value of the boardAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoardAirportCode(String value) {
        this.boardAirportCode = value;
    }

    /**
     * Gets the value of the offAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffAirportCode() {
        return offAirportCode;
    }

    /**
     * Sets the value of the offAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffAirportCode(String value) {
        this.offAirportCode = value;
    }

    /**
     * Gets the value of the ssrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSRCode() {
        return ssrCode;
    }

    /**
     * Sets the value of the ssrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSRCode(String value) {
        this.ssrCode = value;
    }

    /**
     * Gets the value of the lastModifedDateLTC property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifedDateLTC() {
        return lastModifedDateLTC;
    }

    /**
     * Sets the value of the lastModifedDateLTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifedDateLTC(XMLGregorianCalendar value) {
        this.lastModifedDateLTC = value;
    }

    /**
     * Gets the value of the lastModifedDateUTC property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifedDateUTC() {
        return lastModifedDateUTC;
    }

    /**
     * Sets the value of the lastModifedDateUTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifedDateUTC(XMLGregorianCalendar value) {
        this.lastModifedDateUTC = value;
    }

}
