//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.20 at 12:18:50 PM GST 
//


package com.flydubai.dataservices.flight.common.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}BoardAirportCode"/>
 *         &lt;element ref="{}OffAirportCode"/>
 *         &lt;element ref="{}BoardPointOrder"/>
 *         &lt;element ref="{}OffPointOrder"/>
 *         &lt;element ref="{}JourneyTime"/>
 *         &lt;element ref="{}DepartureMetroGroupCode" minOccurs="0"/>
 *         &lt;element ref="{}ArrivalMetroGroupCode" minOccurs="0"/>
 *         &lt;element ref="{}DepTimeLTC"/>
 *         &lt;element ref="{}DepTimeUTC"/>
 *         &lt;element ref="{}ArrivalTimeLTC"/>
 *         &lt;element ref="{}ArrivalTimeUTC"/>
 *         &lt;element ref="{}TrafficRestrictions" minOccurs="0"/>
 *         &lt;element ref="{}LastModifedDateLTC"/>
 *         &lt;element ref="{}LastModifedDateUTC"/>
 *         &lt;element ref="{}LogicalFlightId"/>
 *         &lt;element ref="{}PreSeatStatus"/>
 *         &lt;element ref="{}LIDOpenStatus"/>
 *         &lt;element ref="{}PNLStatus" minOccurs="0"/>
 *         &lt;element ref="{}EquipmentCode" minOccurs="0"/>
 *         &lt;element ref="{}EquipmentVersionCode" minOccurs="0"/>
 *         &lt;element ref="{}SeatTemplateCode" minOccurs="0"/>
 *         &lt;element name="TailNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FlightNumberDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "boardAirportCode",
    "offAirportCode",
    "boardPointOrder",
    "offPointOrder",
    "journeyTime",
    "departureMetroGroupCode",
    "arrivalMetroGroupCode",
    "depTimeLTC",
    "depTimeUTC",
    "arrivalTimeLTC",
    "arrivalTimeUTC",
    "trafficRestrictions",
    "lastModifedDateLTC",
    "lastModifedDateUTC",
    "logicalFlightId",
    "preSeatStatus",
    "lidOpenStatus",
    "pnlStatus",
    "equipmentCode",
    "equipmentVersionCode",
    "seatTemplateCode",
    "tailNumber",
    "flightNumberDetails"
})
@XmlRootElement(name = "Segment")
public class Segment {

    @XmlElement(name = "BoardAirportCode", required = true)
    protected String boardAirportCode;
    @XmlElement(name = "OffAirportCode", required = true)
    protected String offAirportCode;
    @XmlElement(name = "BoardPointOrder")
    protected int boardPointOrder;
    @XmlElement(name = "OffPointOrder")
    protected int offPointOrder;
    @XmlElement(name = "JourneyTime")
    protected int journeyTime;
    @XmlElement(name = "DepartureMetroGroupCode")
    protected String departureMetroGroupCode;
    @XmlElement(name = "ArrivalMetroGroupCode")
    protected String arrivalMetroGroupCode;
    @XmlElement(name = "DepTimeLTC", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar depTimeLTC;
    @XmlElement(name = "DepTimeUTC", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar depTimeUTC;
    @XmlElement(name = "ArrivalTimeLTC", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar arrivalTimeLTC;
    @XmlElement(name = "ArrivalTimeUTC", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar arrivalTimeUTC;
    @XmlElement(name = "TrafficRestrictions")
    protected String trafficRestrictions;
    @XmlElement(name = "LastModifedDateLTC", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifedDateLTC;
    @XmlElement(name = "LastModifedDateUTC", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifedDateUTC;
    @XmlElement(name = "LogicalFlightId")
    protected long logicalFlightId;
    @XmlElement(name = "PreSeatStatus", required = true)
    protected String preSeatStatus;
    @XmlElement(name = "LIDOpenStatus", required = true)
    protected String lidOpenStatus;
    @XmlElement(name = "PNLStatus")
    protected String pnlStatus;
    @XmlElement(name = "EquipmentCode")
    protected String equipmentCode;
    @XmlElement(name = "EquipmentVersionCode")
    protected String equipmentVersionCode;
    @XmlElement(name = "SeatTemplateCode")
    protected String seatTemplateCode;
    @XmlElement(name = "TailNumber", required = true)
    protected String tailNumber;
    @XmlElement(name = "FlightNumberDetails", required = true)
    protected String flightNumberDetails;

    /**
     * Gets the value of the boardAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoardAirportCode() {
        return boardAirportCode;
    }

    /**
     * Sets the value of the boardAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoardAirportCode(String value) {
        this.boardAirportCode = value;
    }

    /**
     * Gets the value of the offAirportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffAirportCode() {
        return offAirportCode;
    }

    /**
     * Sets the value of the offAirportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffAirportCode(String value) {
        this.offAirportCode = value;
    }

    /**
     * Gets the value of the boardPointOrder property.
     * 
     */
    public int getBoardPointOrder() {
        return boardPointOrder;
    }

    /**
     * Sets the value of the boardPointOrder property.
     * 
     */
    public void setBoardPointOrder(int value) {
        this.boardPointOrder = value;
    }

    /**
     * Gets the value of the offPointOrder property.
     * 
     */
    public int getOffPointOrder() {
        return offPointOrder;
    }

    /**
     * Sets the value of the offPointOrder property.
     * 
     */
    public void setOffPointOrder(int value) {
        this.offPointOrder = value;
    }

    /**
     * Gets the value of the journeyTime property.
     * 
     */
    public int getJourneyTime() {
        return journeyTime;
    }

    /**
     * Sets the value of the journeyTime property.
     * 
     */
    public void setJourneyTime(int value) {
        this.journeyTime = value;
    }

    /**
     * Gets the value of the departureMetroGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureMetroGroupCode() {
        return departureMetroGroupCode;
    }

    /**
     * Sets the value of the departureMetroGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureMetroGroupCode(String value) {
        this.departureMetroGroupCode = value;
    }

    /**
     * Gets the value of the arrivalMetroGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalMetroGroupCode() {
        return arrivalMetroGroupCode;
    }

    /**
     * Sets the value of the arrivalMetroGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalMetroGroupCode(String value) {
        this.arrivalMetroGroupCode = value;
    }

    /**
     * Gets the value of the depTimeLTC property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepTimeLTC() {
        return depTimeLTC;
    }

    /**
     * Sets the value of the depTimeLTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepTimeLTC(XMLGregorianCalendar value) {
        this.depTimeLTC = value;
    }

    /**
     * Gets the value of the depTimeUTC property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDepTimeUTC() {
        return depTimeUTC;
    }

    /**
     * Sets the value of the depTimeUTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDepTimeUTC(XMLGregorianCalendar value) {
        this.depTimeUTC = value;
    }

    /**
     * Gets the value of the arrivalTimeLTC property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArrivalTimeLTC() {
        return arrivalTimeLTC;
    }

    /**
     * Sets the value of the arrivalTimeLTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrivalTimeLTC(XMLGregorianCalendar value) {
        this.arrivalTimeLTC = value;
    }

    /**
     * Gets the value of the arrivalTimeUTC property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArrivalTimeUTC() {
        return arrivalTimeUTC;
    }

    /**
     * Sets the value of the arrivalTimeUTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrivalTimeUTC(XMLGregorianCalendar value) {
        this.arrivalTimeUTC = value;
    }

    /**
     * Gets the value of the trafficRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrafficRestrictions() {
        return trafficRestrictions;
    }

    /**
     * Sets the value of the trafficRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrafficRestrictions(String value) {
        this.trafficRestrictions = value;
    }

    /**
     * Gets the value of the lastModifedDateLTC property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifedDateLTC() {
        return lastModifedDateLTC;
    }

    /**
     * Sets the value of the lastModifedDateLTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifedDateLTC(XMLGregorianCalendar value) {
        this.lastModifedDateLTC = value;
    }

    /**
     * Gets the value of the lastModifedDateUTC property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifedDateUTC() {
        return lastModifedDateUTC;
    }

    /**
     * Sets the value of the lastModifedDateUTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifedDateUTC(XMLGregorianCalendar value) {
        this.lastModifedDateUTC = value;
    }

    /**
     * Gets the value of the logicalFlightId property.
     * 
     */
    public long getLogicalFlightId() {
        return logicalFlightId;
    }

    /**
     * Sets the value of the logicalFlightId property.
     * 
     */
    public void setLogicalFlightId(long value) {
        this.logicalFlightId = value;
    }

    /**
     * Gets the value of the preSeatStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreSeatStatus() {
        return preSeatStatus;
    }

    /**
     * Sets the value of the preSeatStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreSeatStatus(String value) {
        this.preSeatStatus = value;
    }

    /**
     * Gets the value of the lidOpenStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIDOpenStatus() {
        return lidOpenStatus;
    }

    /**
     * Sets the value of the lidOpenStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIDOpenStatus(String value) {
        this.lidOpenStatus = value;
    }

    /**
     * Gets the value of the pnlStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPNLStatus() {
        return pnlStatus;
    }

    /**
     * Sets the value of the pnlStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPNLStatus(String value) {
        this.pnlStatus = value;
    }

    /**
     * Gets the value of the equipmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentCode() {
        return equipmentCode;
    }

    /**
     * Sets the value of the equipmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentCode(String value) {
        this.equipmentCode = value;
    }

    /**
     * Gets the value of the equipmentVersionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentVersionCode() {
        return equipmentVersionCode;
    }

    /**
     * Sets the value of the equipmentVersionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentVersionCode(String value) {
        this.equipmentVersionCode = value;
    }

    /**
     * Gets the value of the seatTemplateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeatTemplateCode() {
        return seatTemplateCode;
    }

    /**
     * Sets the value of the seatTemplateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeatTemplateCode(String value) {
        this.seatTemplateCode = value;
    }

    /**
     * Gets the value of the tailNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTailNumber() {
        return tailNumber;
    }

    /**
     * Sets the value of the tailNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTailNumber(String value) {
        this.tailNumber = value;
    }

    /**
     * Gets the value of the flightNumberDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNumberDetails() {
        return flightNumberDetails;
    }

    /**
     * Sets the value of the flightNumberDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNumberDetails(String value) {
        this.flightNumberDetails = value;
    }

}
